title: Just Dhamma
description: Nepali & English Dhamma teachings

baseurl: ""
url: ""

markdown: kramdown

plugins:
  - jekyll-feed

collections:
  ne_posts:
    output: true
    permalink: /ne/:path/

  en_posts:
    output: true
    permalink: /en/:path/

  transcripts:
    output: true
    permalink: /transcripts/:path/

  essays:
    output: true
    permalink: /essays/:path/

  books:
    output: true
    permalink: /books/:path/

defaults:
  - scope:
      path: ""
    values:
      layout: default

exclude:
  - vendor
  - node_modules
  - Gemfile
  - Gemfile.lock
  - README.md
  - .git